"""Add image_generations table

Revision ID: b58d2fcae844
Revises: 9a3b2c1d4e5f
Create Date: 2026-05-21 13:12:47.280850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58d2fcae844'
down_revision: Union[str, Sequence[str], None] = '9a3b2c1d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_generations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('generation_time_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_image_generations_created_at', 'image_generations', ['created_at'], unique=False)
    op.create_index('ix_image_generations_status', 'image_generations', ['status'], unique=False)
    op.create_index('ix_image_generations_user_id', 'image_generations', ['user_id'], unique=False)
    op.create_index('ix_image_generations_user_id_created_at', 'image_generations', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_image_generations_user_id_created_at', table_name='image_generations')
    op.drop_index('ix_image_generations_user_id', table_name='image_generations')
    op.drop_index('ix_image_generations_status', table_name='image_generations')
    op.drop_index('ix_image_generations_created_at', table_name='image_generations')
    op.drop_table('image_generations')
    # ### end Alembic commands ###
