"""Add video_downloads table

Revision ID: c9f8e2b1d3a6
Revises: 32808c74af58
Create Date: 2026-05-25 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f8e2b1d3a6'
down_revision: Union[str, Sequence[str], None] = '32808c74af58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_downloads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('download_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_downloads_created_at', 'video_downloads', ['created_at'], unique=False)
    op.create_index('ix_video_downloads_status', 'video_downloads', ['status'], unique=False)
    op.create_index('ix_video_downloads_user_id', 'video_downloads', ['user_id'], unique=False)
    op.create_index('ix_video_downloads_user_id_created_at', 'video_downloads', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_downloads_user_id_created_at', table_name='video_downloads')
    op.drop_index('ix_video_downloads_user_id', table_name='video_downloads')
    op.drop_index('ix_video_downloads_status', table_name='video_downloads')
    op.drop_index('ix_video_downloads_created_at', table_name='video_downloads')
    op.drop_table('video_downloads')
    # ### end Alembic commands ###
